### PR TITLE
Update kclusters.R

### PR DESCRIPTION
**Pull request by gilbert-neuner**
This change updates the definition of kclusters_simple so that kclusters works on the given example.

### CODE REVIEW

**Comment by jimmylovestea** [comment]
I suspected that this function had gone a bit "stale" over time, so it's great to see someone working on updating it. I haven't tested the function at all, but give me a shout if I can help (I think Monica might have a better sense as to how the function needs to work within the context of the curriculum.

**Comment by gilbert-neuner** [comment]
I think updating the definition of kclusters_simple is sufficient. At the moment, testing kclusters on the example from lab 4H throws an error. I think that k cannot be the second argument of kclusters_simple, otherwise aggregatingFunction2 will try to assign a vector of data to k rather than the desired number of clusters. Adding an argument y to kclusters_simple seems to fix the issue when I've tested it.

**Comment by jimmylovestea** [comment]
You love to see it! Great work on resolving that problem (Which I think has existed for a few years?)

**Comment by rgmobilize** [comment]
well done, Gilbert!

Rob

Sent from my iPhone

On Aug 15, 2022, at 10:52 PM, James Molyneux ***@***.***> wrote:

﻿

You love to see it! Great work on resolving that problem (Which I think has existed for a few years?)

**Pull request closed without merging**
